export const academicprojects = [
  {
    title: 'RIDER:A Traffic Solution',
    description: "Using Android Studio, Java, Firebase Database & Google Map, some basic functionalities of a ride sharing app was implemented. Apart from the typical functionalities, bus service was added in this project. ",
      image: '/images/rider.png',
      tags: ['Android Studio', 'Java', 'Firebase', 'Google Map'],
    source: 'https://github.com/pauljainta/Rider-A-traffic-solution-Software-Development-Project-',
    visit: 'https://github.com/pauljainta/Rider-A-traffic-solution-Software-Development-Project-',
    id: 0,
  },
  {
    title: 'Flickr',
    description:"This was a group project. Some basic functionalities of Flickr was implemented using Java FX and PostGreSQL",
    image: '/images/flickr.png',
    tags: ['Java FX', 'PostGreSQL'],
    source: 'https://github.com/Towsif20/Database-Project-2-2',
    visit: 'https://github.com/Towsif20/Database-Project-2-2',
    id: 1,
  },
  {
    title: 'Automated Car Parking Controller',
    description: "Using Mirocontroller concept and tools like lcd modules,atmega32,servo motor and C++ language,automated car parking system was implemented.",
      image: '/images/parking.png',
      tags: ['C++', 'Microcontroller'],
    source: 'https://github.com/Towsif20/MicroController-Project-3-1',
    visit: 'https://www.youtube.com/watch?v=KceWLTvJtEE&t=74s',
    id: 2,
  },
  {
    title: 'Ray Tracing:Computer Graphics',
    description: "This is a computer graphics project for ray tracing using C++ language",
    image: '/images/raytracing.bmp',
    tags: ['C++', 'Computer Graphics', 'Ray Tracing'],
    source: 'https://github.com/pauljainta/Graphics-Offline-3-Ray-Tracing-Offline-',
    visit: 'https://github.com/pauljainta/Graphics-Offline-3-Ray-Tracing-Offline-',
    id: 3,
  },
  {
    title: 'Rasterization:Computer Graphics',
    description: "This is a computer graphics project for raster based graphics pipeline using C++ language",
    image: '/images/raster.png',
    tags: ['C++', 'Computer Graphics', 'Rasterization'],
    source: 'https://github.com/pauljainta/Raster-Based-Graphics-Pipeline',
    visit: 'https://github.com/pauljainta/Raster-Based-Graphics-Pipeline',
    id: 4,
  },
  {
    title: 'Star Schema in Data Warehouse',
    description: "This project implements the concept of star schema in data warehouse using PostGreSQL",
    image: '/images/star.png',
    tags: ['Database', 'Data Warehouse', 'PostGreSQL'],
    source: 'https://github.com/pauljainta/CSE-453-Assignment',
    visit: 'https://github.com/pauljainta/CSE-453-Assignment',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];